# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a7749d51b981acdcbe19a981803e2b51b0c09394c23d01c153187853d99dbebe72522f72db46c71e23c314d4c6d6c5b6dece867503d18339cca239ac858c70e

test:
  secret_key_base: 8b31264ca88262a5899a2eeb38347096cb2136fbdd6570bbed019a4e26881859f379ab6f8c479db548ccbd29d261df7c9605d1bca7863808c9a943f1d0dee63e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
